name: Build Linux binaries

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install -y libusb-1.0-0-dev libzmq3-dev
      - uses: actions/checkout@v3
      - run: make build
      - uses: actions/upload-artifact@v3
        with:
          name: orbuculum-linux
          path: |
            ofiles/orb*
            Support/gdbtrace.init

