name: Build Linux binaries

on:
  - push
  - pull_request

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libusb-1.0-0-dev libzmq3-dev meson libsdl2-dev libdwarf-dev libdw-dev libelf-dev libcapstone-dev
      
      - uses: actions/checkout@v3
      - run: meson setup ./build
      - run: ninja -C ./build
      - run: meson install -C ./build --destdir ./install
      - uses: actions/upload-artifact@v3
        with:
          name: orbuculum-linux
          path: build/install/**/*
          if-no-files-found: error


